ALTER TABLE violations
  ADD COLUMN ai_buffer DOUBLE NULL,
  ADD COLUMN mitigation_score DOUBLE NULL,
  ADD COLUMN ai_windows BIGINT NULL,
  ADD COLUMN ai_high_windows BIGINT NULL,
  ADD COLUMN probability_trail VARBINARY(1024) NULL;

ALTER TABLE player_logins
  ADD COLUMN ai_high_windows BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN ai_windows BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN prob_low BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN prob_mid BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN prob_high BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN ai_state_at BIGINT NOT NULL DEFAULT 0;
